"""add user migration

Revision ID: 82611ca98fe5
Revises: 
Create Date: 2020-12-09 10:26:57.305662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82611ca98fe5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('ix_game_name', table_name='game')
    op.create_unique_constraint(None, 'game', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='unique')
    op.create_index('ix_game_name', 'game', ['name'], unique=1)
    op.drop_table('guest')
    # ### end Alembic commands ###
